export default {
  ca: 'radial-gradient(silver, skyblue)',
  cb: 'radial-gradient(black, cornsilk)',
  cc: 'radial-gradient(gold, yellow)',
  cd: 'radial-gradient(orange, greenyellow, lightgreen)',
  ce: 'radial-gradient(indigo,blue)',
  cf: 'radial-gradient(magenta, darkorange, red)',
  cg: 'radial-gradient(saddlebrown,darkgreen)',
  ch: 'radial-gradient(mediumorchid, violet, lightpink)',
  la: 'linear-gradient(silver, skyblue)',
  lb: 'linear-gradient(black, cornsilk)',
  lc: 'linear-gradient(gold, yellow)',
  ld: 'linear-gradient(orange, greenyellow, lightgreen)',
  le: 'linear-gradient(indigo,blue)',
  lf: 'linear-gradient(magenta, darkorange, red)',
  lg: 'linear-gradient(saddlebrown,darkgreen)',
  lh: 'linear-gradient(mediumorchid, violet, lightpink)',
};
